---
version: "1.0"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --label-enable --cleanup --schedule "0 0 11 * * *"
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      default:
        ipv4_address: 172.20.1.2
    ports:
      - 8989:8989
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/sonarr/config:/config
      - ${DOWNLOADS}/torrents:/downloads
      - ${DATA}:/data
    restart: always
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      default:
        ipv4_address: 172.20.1.3
    ports:
      - 7878:7878
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/radarr/config:/config
      - ${DOWNLOADS}/torrents:/downloads
      - ${DATA}:/data
    restart: always
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    networks:
      default:
        ipv4_address: 172.20.1.4
    ports:
      - 6767:6767
    depends_on:
      - sonarr
      - radarr
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/bazarr/config:/config
      - ${DATA}:/data
    restart: always
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks:
      default:
        ipv4_address: 172.20.1.15
    ports:
      - 9117:9117
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/jackett/config:/config
      - ${DOWNLOADS}/torrents:/downloads
    restart: always
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    networks:
      default:
        ipv4_address: 172.20.1.5
    ports:
      - 8096:8096
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ${CONTAINERS}/jellyfin/config:/config
      - ${CONTAINERS}/jellyfin/cache:/cache
      - ${DATA}:/data
    restart: always
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      default:
        ipv4_address: 172.20.1.6
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ${CONTAINERS}/jellyseerr:/app/config
    restart: always
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      default:
        ipv4_address: 172.20.1.7
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8855
    volumes:
      - ${CONTAINERS}/qbit/config:/config
      - ${DOWNLOADS}/torrents:/downloads
    ports:
      - 8855:8855
      - 6881:6881
      - 6881:6881/udp
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: always
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    networks:
      default:
        ipv4_address: 172.20.1.8
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 80:3000
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: always
    volumes:
      - ${CONTAINERS}/homepage/config:/app/config
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      default:
        ipv4_address: 172.20.2.2
    ports:
      - 9000:9000
      - 8000:8000
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINERS}/portainer:/data
  portainer_agent:
    image: portainer/agent
    container_name: portainer-agent
    networks:
      default:
        ipv4_address: 172.20.2.3
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
